import React from 'react';

const ScoreInfoPopup = ({ open, onClose }) => {
  if (!open) return null;

  return (
    <div
      className="score-info-popup"
      style={{ display: 'flex' }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="score-info-card">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px' }}>
          <div style={{ fontSize: '15px', fontWeight: 700, color: '#3A2700' }}>
            📈 How is the Health Score calculated?
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'rgba(58,39,0,.08)',
              border: 'none',
              width: '28px',
              height: '28px',
              borderRadius: '50%',
              cursor: 'pointer',
              fontSize: '14px',
              fontFamily: 'Poppins, sans-serif',
            }}
          >
            ✕
          </button>
        </div>

        <div style={{ fontSize: '12px', color: '#5C3F18', lineHeight: 1.65, marginBottom: '14px' }}>
          The <strong>PoopSense AI Health Score (0–100)</strong> is computed by Claude Vision AI by analysing
          your dog's stool photograph across 5 key parameters.
        </div>

        {[
          { icon: '🟡', title: 'Colour (20 pts)', desc: 'Healthy = medium brown. Abnormal colours (black, red, grey, yellow, green) lower the score.' },
          { icon: '🧽', title: 'Consistency (25 pts)', desc: 'Bristol Scale 3–4 is ideal. Too watery or too hard each reduce the score significantly.' },
          { icon: '🔬', title: 'Shape (15 pts)', desc: 'Well-formed sausage shape is ideal. Fragmented, pellet-like, or formless shapes indicate digestive issues.' },
          { icon: '🔍', title: 'Contents (20 pts)', desc: 'Presence of mucus, blood, parasites, undigested food or foreign material reduces the score.' },
          { icon: '📊', title: 'Risk Pattern (20 pts)', desc: 'Overall clinical risk assessment. Detected patterns such as repeated soft stools, urgency, or blood reduce this score.' },
        ].map(({ icon, title, desc }) => (
          <div key={title} className="score-band" style={{ background: '#EAF8EF' }}>
            <div style={{ fontSize: '20px' }}>{icon}</div>
            <div>
              <div style={{ fontSize: '12px', fontWeight: 700, color: '#195C30' }}>{title}</div>
              <div style={{ fontSize: '11px', color: '#555' }}>{desc}</div>
            </div>
          </div>
        ))}

        <div style={{ fontSize: '12px', fontWeight: 600, color: '#3A2700', margin: '14px 0 8px' }}>Score Bands</div>

        {[
          { icon: '✅', title: '75–100 — Healthy', desc: 'Stool looks normal. Routine diet and hydration are fine.', bg: '#EAF8EF', color: '#195C30' },
          { icon: '⚠️', title: '50–74 — Monitor', desc: 'Some concern noted. Keep an eye, offer bland food. Visit vet if it continues.', bg: '#FFF8EE', color: '#C47808' },
          { icon: '🚫', title: '0–49 — Urgent', desc: 'Significant abnormality detected. Consult your vet as soon as possible.', bg: '#FFF0EE', color: '#AD2218' },
        ].map(({ icon, title, desc, bg, color }) => (
          <div key={title} className="score-band" style={{ background: bg }}>
            <div style={{ fontSize: '18px' }}>{icon}</div>
            <div>
              <div style={{ fontSize: '12px', fontWeight: 700, color }}>{title}</div>
              <div style={{ fontSize: '11px', color: '#555' }}>{desc}</div>
            </div>
          </div>
        ))}

        <div style={{ background: '#FFF8EE', borderRadius: '10px', padding: '10px 12px', marginTop: '12px', fontSize: '11px', color: '#5C3F18', lineHeight: 1.5 }}>
          🫶 This score is generated by AI for informational purposes only. Please always verify with your veterinarian.
        </div>
      </div>
    </div>
  );
};

export default ScoreInfoPopup;
