// src/utils/toolsPdfGenerator.js
// PDF generation for Doglicious free tools using pdfmake.
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake ? pdfFonts.pdfMake.vfs : pdfFonts.vfs;

// ── Shared Palette ────────────────────────────────────────────────────
const C = {
  brand:   '#3D2B00',
  green:   '#1A7A45',
  amber:   '#C47A0A',
  red:     '#A01A1A',
  blue:    '#1a4fa0',
  gold:    '#C4A87A',
  light:   '#FBF6EC',
  gray:    '#8B6B3D',
  border:  '#EDE8DC',
  white:   '#FFFFFF',
  bgGreen: '#EBF7F0',
  bgAmber: '#FEF5E4',
  bgRed:   '#FCF0F0',
};

const fmt = (n) => 'Rs. ' + Math.round(n).toLocaleString('en-IN');

// Helper to remove emoji and trim text
const stripEmoji = (text) => text.replace(/^[^\w\s]*\s*/, '').trim();

// ── Shared Helpers ────────────────────────────────────────────────────

function pageHeader(toolName) {
  return {
    columns: [
      { text: 'Doglicious', fontSize: 18, bold: true, color: C.brand, margin: [0, 0, 0, 0] },
      { text: toolName, fontSize: 10, color: C.gray, alignment: 'right', margin: [0, 6, 0, 0] },
    ],
    margin: [0, 0, 0, 4],
  };
}

function divider() {
  return {
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.8, lineColor: C.gold, strokeOpacity: 0.6 }],
    margin: [0, 4, 0, 12],
  };
}

function sectionHeader(title) {
  return {
    stack: [
      { text: title.toUpperCase(), fontSize: 8.5, bold: true, color: C.gray, letterSpacing: 1 },
      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.8, lineColor: C.gold, strokeOpacity: 0.4 }], margin: [0, 3, 0, 8] },
    ],
  };
}

function infoRow(label, value, valueColor) {
  return {
    columns: [
      { text: label, fontSize: 11, color: C.gray, width: 180 },
      { text: value, fontSize: 11, bold: true, color: valueColor || C.brand },
    ],
    margin: [0, 0, 0, 6],
  };
}

function statsTable(rows) {
  return {
    table: {
      widths: ['*', '*'],
      body: rows.map(([label, val, sub]) => [
        { stack: [{ text: label, fontSize: 9, color: C.gray }], fillColor: C.light, margin: [8, 6, 8, 6] },
        { stack: [{ text: val, fontSize: 14, bold: true, color: C.brand }, { text: sub || '', fontSize: 8, color: C.gray }], fillColor: C.light, margin: [8, 6, 8, 6] },
      ]),
    },
    layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border },
    margin: [0, 0, 0, 14],
  };
}

function tipsSection(tips) {
  return {
    stack: [
      sectionHeader('Nutrition Recommendations'),
      ...tips.map(tip => ({
        columns: [
          { text: '•', fontSize: 16, width: 20, bold: true, color: C.green },
          { text: tip.text.replace(/<[^>]+>/g, ''), fontSize: 10, color: C.brand, width: '*', lineHeight: 1.4 },
        ],
        margin: [0, 0, 0, 8],
        unbreakable: true,
      })),
    ],
  };
}

function disclaimer() {
  return {
    table: {
      widths: ['*'],
      body: [[{
        text: 'DISCLAIMER: Please consult your veterinarian before starting any treatment, supplement, or medication, or making changes to your pet\'s diet, exercise, or lifestyle. Individual health needs may vary.',
        fontSize: 9,
        color: '#5C3F18',
        lineHeight: 1.5,
        margin: [10, 8, 10, 8],
        bold: true,
      }]],
    },
    layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => '#E5D4B0', vLineColor: () => '#E5D4B0', fillColor: () => '#FEF5E4' },
    margin: [0, 16, 0, 0],
  };
}

function footerNote() {
  return {
    text: 'Generated by Doglicious · doglicious.in · For informational purposes only',
    fontSize: 8,
    color: C.gray,
    alignment: 'center',
    margin: [0, 16, 0, 0],
  };
}

function buildAndDownload(docDef, filename) {
  pdfMake.createPdf(docDef).download(filename);
}

// ─────────────────────────────────────────────────────────────────────
// 1. BMI CALCULATOR PDF
// ─────────────────────────────────────────────────────────────────────
export function downloadBmiPdf(result) {
  const categoryColors = {
    underweight: C.blue,
    ideal: C.green,
    overweight: C.amber,
    obese: C.red,
  };
  const catColor = categoryColors[result.category] || C.brand;

  const content = [
    pageHeader('Dog BMI & Body Condition Report'),
    divider(),
    { text: 'Dog Body Condition Report', fontSize: 20, bold: true, color: C.brand, margin: [0, 0, 0, 4] },
    { text: `Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, fontSize: 10, color: C.gray, margin: [0, 0, 0, 16] },

    sectionHeader('Result'),
    {
      table: {
        widths: ['*'],
        body: [[{
          stack: [
            { text: result.vd.label, fontSize: 16, bold: true, color: catColor },
            {
              text: `BCS ${result.bcs}/9  ·  Current: ${result.weight}kg  ·  Ideal range: ${result.range.min}–${result.range.max}kg`,
              fontSize: 10, color: C.gray, margin: [0, 4, 0, 0],
            },
          ],
          margin: [12, 10, 12, 10],
        }]],
      },
      layout: { hLineWidth: () => 1, vLineWidth: () => 1, hLineColor: () => catColor, vLineColor: () => catColor, fillColor: () => result.vd.bg },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Dog Details'),
    infoRow('Current Weight', `${result.weight} kg`),
    infoRow('Age', result.age ? `${result.age} years` : 'Not provided'),
    infoRow('Breed Size', result.size.charAt(0).toUpperCase() + result.size.slice(1)),
    infoRow('Sex', result.sex ? result.sex.charAt(0).toUpperCase() + result.sex.slice(1) : 'Not provided'),
    infoRow('Body Condition Score', `${result.bcs} / 9`),
    { text: '', margin: [0, 0, 0, 6] },

    sectionHeader('Weight Analysis'),
    statsTable([
      ['Current Weight', `${result.weight} kg`, ''],
      ['Ideal Weight Range', `${result.range.min}–${result.range.max} kg`, 'target range'],
      ['Variance from Ideal', `${result.diff > 0 ? '+' : ''}${Math.round(result.diff * 10) / 10} kg`, result.diff > 0 ? 'above ideal' : result.diff < 0 ? 'below ideal' : 'at ideal'],
      ['Goal Timeline', result.weeks > 0 ? `${result.weeks} weeks` : 'At goal', 'at safe pace'],
    ]),

    sectionHeader('Weight Goal Plan'),
    infoRow('Target Weight', `${result.idealTarget} kg`),
    infoRow('Safe Loss/Gain Rate', '1–2% body weight per week'),
    infoRow('Weekly Change', result.category === 'ideal' ? 'Maintain current weight' : `${result.category === 'underweight' ? 'Gain' : 'Lose'} ~${result.safeWeekly} kg/week`),
    infoRow('Estimated Timeline', result.weeks > 0 ? `${result.weeks} weeks` : 'Already at goal!'),
    { text: '', margin: [0, 0, 0, 6] },

    tipsSection(result.vd.tips),
    disclaimer(),
    footerNote(),
  ];

  buildAndDownload({
    content,
    styles: {
      sectionTitle: { fontSize: 8.5, bold: true, color: C.gray, letterSpacing: 1 },
    },
    defaultStyle: { font: 'Roboto', fontSize: 11, color: C.brand },
    pageMargins: [40, 50, 40, 40],
  }, `Doglicious-BMI-Report.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// 2. FEEDING CALCULATOR PDF
// ─────────────────────────────────────────────────────────────────────
export function downloadFeedingPdf(result, aiTip) {
  const AGE_LABELS = { puppy: 'Puppy (0–12 months)', adult: 'Adult (1–7 years)', senior: 'Senior (7+ years)', nursing: 'Nursing / Pregnant' };
  const HOME_LABELS = { studio: 'Studio / 1BHK', '2bhk': '2BHK', '3bhk': '3BHK+', house: 'Independent House' };
  const ACT_LABELS = ['Sedentary', 'Low Activity', 'Moderate', 'Active', 'Very Active'];

  const content = [
    pageHeader('Dog Feeding Calculator Report'),
    divider(),
    { text: 'Daily Feeding Plan', fontSize: 20, bold: true, color: C.brand, margin: [0, 0, 0, 4] },
    { text: `Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, fontSize: 10, color: C.gray, margin: [0, 0, 0, 16] },

    sectionHeader('Feeding Summary'),
    {
      table: {
        widths: ['*', '*'],
        body: [
          [
            { stack: [{ text: `${result.dailyG}g`, fontSize: 28, bold: true, color: C.green }, { text: 'per day', fontSize: 10, color: C.gray }], margin: [12, 12, 12, 12], alignment: 'center' },
            { stack: [{ text: `${result.dailyCal} kcal`, fontSize: 28, bold: true, color: C.amber }, { text: 'per day', fontSize: 10, color: C.gray }], margin: [12, 12, 12, 12], alignment: 'center' },
          ],
        ],
      },
      layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border, fillColor: () => C.light },
      margin: [0, 0, 0, 10],
    },
    {
      table: {
        widths: ['*'],
        body: [[{
          text: `${result.meals} meals per day  ·  ${result.perMeal}g per meal`,
          fontSize: 13, bold: true, color: C.brand, alignment: 'center', margin: [10, 8, 10, 8],
        }]],
      },
      layout: { hLineWidth: () => 1, vLineWidth: () => 1, hLineColor: () => C.green, vLineColor: () => C.green, fillColor: () => C.bgGreen },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Dog Details'),
    infoRow('Weight', `${result.w} kg`),
    infoRow('Age Group', AGE_LABELS[result.age] || result.age),
    infoRow('Breed', result.breedName),
    infoRow('Current Food Type', result.food === 'kibble' ? 'Dry Kibble' : 'Fresh / Home Food'),
    infoRow('Home Type', HOME_LABELS[result.home] || result.home),
    infoRow('Daily Walk Distance', `${result.totalWalk} km/day`),
    infoRow('Activity Level', ACT_LABELS[result.actLevel] || 'Moderate'),
    { text: '', margin: [0, 0, 0, 6] },

    sectionHeader('Nutritionist Tip'),
    {
      table: {
        widths: ['*'],
        body: [[{
          stack: [
            { text: 'AI-POWERED NUTRITIONIST INSIGHT', fontSize: 9, bold: true, color: C.green, margin: [0, 0, 0, 4], letterSpacing: 0.5 },
            { text: aiTip || 'Personalised tip unavailable. Please consult your veterinarian for breed-specific advice.', fontSize: 11, color: C.brand, lineHeight: 1.5 },
          ],
          margin: [12, 10, 12, 10],
        }]],
      },
      layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border, fillColor: () => C.bgGreen },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Feeding Tips'),
    ...[
      { text: 'Weigh food with a kitchen scale for the first 2 weeks to build visual portion awareness.' },
      { text: 'Always have fresh water available. In Indian summers, add ice cubes to keep water cool.' },
      { text: 'Feed at the same times daily — consistent meal schedules improve digestion.' },
      { text: 'Monitor body weight monthly. Adjust portions by 10% if weight drifts from ideal.' },
    ].map(tip => ({
      columns: [
        { text: '•', fontSize: 16, width: 20, bold: true, color: C.green },
        { text: tip.text, fontSize: 10, color: C.brand, width: '*', lineHeight: 1.4 },
      ],
      margin: [0, 0, 0, 8],
      unbreakable: true,
    })),

    disclaimer(),
    footerNote(),
  ];

  buildAndDownload({
    content,
    defaultStyle: { font: 'Roboto', fontSize: 11, color: C.brand },
    pageMargins: [40, 50, 40, 40],
  }, `Doglicious-Feeding-Plan.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// 3. COST CALCULATOR PDF
// ─────────────────────────────────────────────────────────────────────
export function downloadCostPdf(result) {
  const verdictColor = result.verdict.cls === 'cheaper' ? C.green : C.amber;

  const content = [
    pageHeader('Dog Food Cost Calculator Report'),
    divider(),
    { text: 'Kibble vs Fresh Food — Cost Comparison', fontSize: 20, bold: true, color: C.brand, margin: [0, 0, 0, 4] },
    { text: `Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, fontSize: 10, color: C.gray, margin: [0, 0, 0, 16] },

    sectionHeader('Verdict'),
    {
      table: {
        widths: ['*'],
        body: [[{
          text: result.verdict.msg.replace(/<[^>]+>/g, ''),
          fontSize: 13, bold: true, color: verdictColor, lineHeight: 1.4, margin: [12, 10, 12, 10],
        }]],
      },
      layout: { hLineWidth: () => 1, vLineWidth: () => 1, hLineColor: () => verdictColor, vLineColor: () => verdictColor, fillColor: () => result.verdict.cls === 'cheaper' ? C.bgGreen : '#FEF5E4' },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Cost Comparison'),
    {
      table: {
        widths: [100, '*', '*'],
        body: [
          [
            { text: 'Period', fontSize: 10, bold: true, color: C.gray, fillColor: C.light, margin: [8, 6, 8, 6] },
            { text: result.brand || 'Kibble', fontSize: 10, bold: true, color: C.gray, fillColor: C.light, margin: [8, 6, 8, 6] },
            { text: 'Fresh Food', fontSize: 10, bold: true, color: C.green, fillColor: C.light, margin: [8, 6, 8, 6] },
          ],
          [
            { text: 'Daily', fontSize: 11, margin: [8, 6, 8, 6] },
            { text: fmt(result.kibbleDaily), fontSize: 11, color: C.brand, margin: [8, 6, 8, 6] },
            { text: fmt(result.freshDaily), fontSize: 11, color: C.green, bold: true, margin: [8, 6, 8, 6] },
          ],
          [
            { text: 'Monthly', fontSize: 11, margin: [8, 6, 8, 6] },
            { text: fmt(result.kibbleMonthly), fontSize: 11, color: C.brand, margin: [8, 6, 8, 6] },
            { text: fmt(result.freshMonthly), fontSize: 11, color: C.green, bold: true, margin: [8, 6, 8, 6] },
          ],
          [
            { text: 'Yearly', fontSize: 11, bold: true, margin: [8, 6, 8, 6] },
            { text: fmt(result.kibbleYearly), fontSize: 11, bold: true, color: C.brand, margin: [8, 6, 8, 6] },
            { text: fmt(result.freshYearly), fontSize: 11, bold: true, color: C.green, margin: [8, 6, 8, 6] },
          ],
          [
            { text: 'Annual Difference', fontSize: 11, bold: true, margin: [8, 6, 8, 6] },
            { text: '', margin: [8, 6, 8, 6] },
            { text: result.verdict.savings, fontSize: 11, bold: true, color: verdictColor, margin: [8, 6, 8, 6] },
          ],
        ],
      },
      layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Hidden Costs of Kibble (Annual Estimates)'),
    ...[
      { label: 'Dental cleaning / scaling', sub: 'Kibble builds tartar 3x faster', cost: fmt(5500) },
      { label: 'Allergy vet visits', sub: 'Grain & preservative reactions common', cost: fmt(4000) },
      { label: 'Digestive medications', sub: 'IBD, loose stools, gas', cost: fmt(2750) },
      { label: 'Skin & coat supplements', sub: 'Omega-3 deficiency from ultra-processing', cost: fmt(2100) },
      { label: 'Potential vet savings with fresh', sub: 'Fewer vet visits, better digestion, longer life', cost: `Save ${fmt(14000)}/yr`, positive: true },
    ].map(row => ({
      columns: [
        {
          stack: [
            { text: row.label, fontSize: 11, bold: true, color: C.brand },
            { text: row.sub, fontSize: 9, color: C.gray },
          ],
          width: '*',
        },
        { text: row.cost, fontSize: 11, bold: true, color: row.positive ? C.green : C.red, width: 120, alignment: 'right', margin: [0, 4, 0, 0] },
      ],
      margin: [0, 0, 0, 10],
      unbreakable: true,
    })),

    disclaimer(),
    footerNote(),
  ];

  buildAndDownload({
    content,
    defaultStyle: { font: 'Roboto', fontSize: 11, color: C.brand },
    pageMargins: [40, 50, 40, 40],
  }, `Doglicious-Cost-Comparison.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// 4. AGE CALCULATOR PDF
// ─────────────────────────────────────────────────────────────────────
export function downloadAgePdf(result) {
  const STAGE_COLORS = {
    puppy: '#4CAF50', adolescent: '#FF9800', adult: '#2196F3',
    senior: '#9C27B0', geriatric: '#E91E63',
  };
  const SIZE_LABELS = {
    small: 'Small (<10 kg)', medium: 'Medium (10–25 kg)',
    large: 'Large (25–45 kg)', giant: 'Giant (>45 kg)',
  };
  const stageColor = STAGE_COLORS[result.stage] || C.brand;

  const content = [
    pageHeader('Dog Age Calculator Report'),
    divider(),
    { text: `${result.name}'s Age Report`, fontSize: 20, bold: true, color: C.brand, margin: [0, 0, 0, 4] },
    { text: `Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, fontSize: 10, color: C.gray, margin: [0, 0, 0, 16] },

    sectionHeader('Result'),
    {
      table: {
        widths: ['*'],
        body: [[{
          stack: [
            { text: `${result.humanAge} Human Years`, fontSize: 28, bold: true, color: stageColor, alignment: 'center' },
            { text: stripEmoji(result.sd.label), fontSize: 13, color: C.gray, alignment: 'center', margin: [0, 4, 0, 0] },
          ],
          margin: [12, 14, 12, 14],
        }]],
      },
      layout: { hLineWidth: () => 1, vLineWidth: () => 1, hLineColor: () => stageColor, vLineColor: () => stageColor, fillColor: () => C.light },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Dog Details'),
    infoRow('Name', result.name),
    infoRow('Dog Age', `${result.years} year${result.years !== 1 ? 's' : ''}${result.months > 0 ? ' ' + result.months + ' month' + (result.months !== 1 ? 's' : '') : ''}`),
    infoRow('Breed Size', SIZE_LABELS[result.size] || result.size),
    infoRow('Equivalent Human Age', `${result.humanAge} years`),
    infoRow('Life Stage', stripEmoji(result.sd.label)),
    { text: '', margin: [0, 0, 0, 6] },

    tipsSection(result.sd.tips),
    disclaimer(),
    footerNote(),
  ];

  buildAndDownload({
    content,
    defaultStyle: { font: 'Roboto', fontSize: 11, color: C.brand },
    pageMargins: [40, 50, 40, 40],
  }, `Doglicious-Age-Report-${result.name}.pdf`);
}

// ─────────────────────────────────────────────────────────────────────
// 5. HEALTH QUIZ PDF
// ─────────────────────────────────────────────────────────────────────
export function downloadHealthQuizPdf(result, aiTip) {
  function scoreColor(s) {
    if (s >= 8) return C.green;
    if (s >= 6) return C.amber;
    if (s >= 4) return '#D97706';
    return C.red;
  }

  function overallColor(pct) {
    if (pct >= 80) return C.green;
    if (pct >= 60) return '#2196F3';
    if (pct >= 40) return C.amber;
    return C.red;
  }

  function overallLabel(pct) {
    if (pct >= 80) return 'Excellent Health';
    if (pct >= 60) return 'Good Health';
    if (pct >= 40) return 'Needs Attention';
    return 'Health Alert';
  }

  function progressBar(label, score, max) {
    const w = 435;
    const fillW = Math.max(4, (score / max) * w);
    const color = scoreColor(score);
    return {
      stack: [
        {
          columns: [
            { text: label, fontSize: 10, color: C.brand, width: '*' },
            { text: `${score}/${max}`, fontSize: 10, bold: true, color: color, width: 40, alignment: 'right' },
          ],
          margin: [0, 0, 0, 3],
        },
        {
          canvas: [
            { type: 'line', x1: 0, y1: 0, x2: w, y2: 0, lineWidth: 6, lineColor: C.border, lineCap: 'round' },
            { type: 'line', x1: 0, y1: 0, x2: fillW, y2: 0, lineWidth: 6, lineColor: color, lineCap: 'round' },
          ],
          margin: [0, 0, 0, 8],
        },
      ],
      unbreakable: true,
    };
  }

  const weakAreas = result.bd.filter(b => b.score < 7).sort((a, b) => a.score - b.score);
  const oColor = overallColor(result.score);

  const content = [
    pageHeader('Dog Health Quiz Report'),
    divider(),
    { text: `${result.dog.name}'s Health Score Report`, fontSize: 20, bold: true, color: C.brand, margin: [0, 0, 0, 4] },
    { text: `Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, fontSize: 10, color: C.gray, margin: [0, 0, 0, 16] },

    sectionHeader('Overall Score'),
    {
      table: {
        widths: ['*'],
        body: [[{
          stack: [
            { text: `${result.score} / 100`, fontSize: 32, bold: true, color: oColor, alignment: 'center' },
            { text: overallLabel(result.score), fontSize: 14, color: oColor, alignment: 'center', margin: [0, 4, 0, 0] },
          ],
          margin: [12, 14, 12, 14],
        }]],
      },
      layout: { hLineWidth: () => 1, vLineWidth: () => 1, hLineColor: () => oColor, vLineColor: () => oColor, fillColor: () => C.light },
      margin: [0, 0, 0, 16],
    },

    sectionHeader('Dog Profile'),
    infoRow('Name', result.dog.name),
    infoRow('Breed', result.dog.breed),
    infoRow('Age', result.dog.age),
    infoRow('Weight', result.dog.weight ? `${result.dog.weight} kg` : 'Not provided'),
    { text: '', margin: [0, 0, 0, 6] },

    sectionHeader('Health Breakdown'),
    ...result.bd.map(b => progressBar(b.cat, b.score, b.max)),
    { text: '', margin: [0, 0, 0, 6] },
  ];

  if (weakAreas.length > 0) {
    content.push(sectionHeader('Top Priorities to Improve'));
    weakAreas.slice(0, 5).forEach(w => {
      content.push({
        table: {
          widths: ['*'],
          body: [[
            {
              stack: [
                { text: `${w.cat} (${w.score}/10)`, fontSize: 10, bold: true, color: scoreColor(w.score) },
                { text: w.tip, fontSize: 10, color: C.brand, lineHeight: 1.4, margin: [0, 2, 0, 0] },
              ],
              margin: [8, 6, 8, 6],
            },
          ]],
        },
        layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border, fillColor: () => C.light },
        margin: [0, 0, 0, 8],
        unbreakable: true,
      });
    });
    content.push({ text: '', margin: [0, 0, 0, 6] });
  }

  content.push(sectionHeader('Personalised Health Insight'));
  content.push({
    table: {
      widths: ['*'],
      body: [[{
        stack: [
          { text: 'AI-POWERED NUTRITIONIST INSIGHT', fontSize: 9, bold: true, color: C.green, margin: [0, 0, 0, 4], letterSpacing: 0.5 },
          { text: aiTip || 'Personalised tip unavailable. Please consult your veterinarian.', fontSize: 11, color: C.brand, lineHeight: 1.5 },
        ],
        margin: [12, 10, 12, 10],
      }]],
    },
    layout: { hLineWidth: () => 0.5, vLineWidth: () => 0.5, hLineColor: () => C.border, vLineColor: () => C.border, fillColor: () => C.bgGreen },
    margin: [0, 0, 0, 16],
  });

  content.push(disclaimer());
  content.push(footerNote());

  buildAndDownload({
    content,
    defaultStyle: { font: 'Roboto', fontSize: 11, color: C.brand },
    pageMargins: [40, 50, 40, 40],
  }, `Doglicious-Health-Score-${result.dog.name}.pdf`);
}
